config/routes.rb
Sample4App::Application.routes.draw do
  resources :stores 
  resources :sessions, only: [:new, :create, :destroy]
  resources :articles, only: [:create, :destroy, :new, :index, :show]
  resources :segments do
    resources :stores
    resources :articles
  end
  resources :stores do 
    resources :articles, only: :index
  end
  resources :articles do
    resources :articles_images
  end
  root  'static_pages#home'
  match '/index_eat',  to: 'segments#index_eat',            via: 'get'
  match '/index_shopping',  to: 'segments#index_shopping',            via: 'get'
  match '/signup',  to: 'stores#new',            via: 'get'
  match '/signin',  to: 'sessions#new',         via: 'get'
  match '/signout', to: 'sessions#destroy',     via: 'delete'
  match '/about',   to: 'static_pages#about',   via: 'get'

end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :store
	belongs_to :segment
	default_scope -> { order('created_at DESC') }
	validates :herenowtitle, presence: true
	validates :title, presence: true
	validates :content, presence: true
	validates :store_id, presence: true
	mount_uploader :image, ImageUploader
end

app/models/articles_image.rb
class ArticlesImage < ActiveRecord::Base
	belongs_to :article

	IMAGE_TYPES = { "image/jpeg" => "jpg", "image/gif => "gif", "image/png" => "png" }
    def extension
    	IMAGE_TYPES[content_type]
    end
end

app/models/location.rb
class Location < ActiveRecord::Base
end

app/models/segment.rb
class Segment < ActiveRecord::Base
	has_many :stores
	has_many :articles
end

app/models/store.rb
class Store < ActiveRecord::Base
	has_many :articles, dependent: :destroy
	belongs_to :segment
	accepts_nested_attributes_for :segment
	before_save { self.email = email.downcase }
	before_create :create_remember_token
	validates :name, presence: true, length: { maximum: 50 }
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, presence: true, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_sensitive: false }
	validates :address, presence: true
	validates :tell, presence: true
	validates :url, presence: true
	has_secure_password
	validates :password, length: { minimum: 6 }

  def Store.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def Store.encrypt(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = Store.encrypt(Store.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :signed_in_store,  only:[:create, :destroy, :new, :index]

  def new
  	  @article = Article.new
  end

  def show
      @article = Article.find(params[:id])
  end

  def index
      @articles = current_store.articles.paginate(page: params[:page])
  end

  def index_eat
      @segments = Segment.where(name: '食事')
      @articles = segments.articles
  end

  def create
  	  @article = current_store.articles.build(article_params)
    if @article.save
      flash[:success] = "投稿完了!"
      redirect_to root_url
    else
      render 'static_pages/home'
    end
  end

  def destroy
  end

  private

    def article_params
      params.require(:article).permit( :content, :herenowtitle, :title, :image )
    end
end

app/controllers/locations_controller.rb
class LocationsController < ApplicationController

  def new
    @location = Location.new
  end

  def create
    @location = Location.new(location_params)
    @location.save
    end
  end	

  private

    def location_params
      params.require(:location).permit(:longitude, :latitude, :address)
    end
end

app/controllers/segments_controller.rb
class SegmentsController < ApplicationController
  def index_eat
  	@segment = Segment.where(name: '食事')
  end

  def index_shopping
  	@segments = Segment.where(name: 'ショッピング')
  end

  def about
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    store = Store.find_by(email: params[:session][:email].downcase)
    if store && store.authenticate(params[:session][:password])
      sign_in store
      redirect_to new_article_path
    else
      flash.now[:error] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
  	sign_out
  	redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@articles = Article.all
  end

  def about
  end

  
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def show
    @store = Store.find(params[:id])
    @articles = @store.articles.paginate(page: params[:page])
  end

  def new
  	 @store = Store.new
     @store.build_segment
  end

  def create
    @store = Store.new(store_params)
    if @store.save
      sign_in @store
      flash[:success] = "Welcome to the BeansStreet!"
      redirect_to @store
    else
      render 'new'
    end
  end

  private

    def store_params
      params.require(:store).permit(:name, :email, :address, :tell, :url, :password, :password_confirmation, :segment_id, :segment_attributes)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper

  # ページごとの完全なタイトルを返します。
  def full_title(page_title)
    base_title = "Ruby on Rails Tutorial Sample App"
    if page_title.empty?
      base_title
    else
      "#{base_title} | #{page_title}"
    end
  end
 end

app/helpers/sessions_helper.rb
module SessionsHelper

  def sign_in(store)
    remember_token = Store.new_remember_token
    cookies.permanent[:remember_token] = remember_token
    store.update_attribute(:remember_token, Store.encrypt(remember_token))
    self.current_store = store
  end
  
  def signed_in?
    !current_store.nil?
  end

  def current_store=(store)
    @current_store = store
  end

  def current_store
    remember_token = Store.encrypt(cookies[:remember_token])
    @current_store ||= Store.find_by(remember_token: remember_token)
  end

  def current_store?(store)
    store == current_store
  end

  def signed_in_store
    unless signed_in?
      redirect_to signin_url, notice: "Please sign in."
    end
  end

  def sign_out
    self.current_store = nil
    cookies.delete(:remember_token)
  end

end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/articles/_article.html.erb
<li>
  <span class="content"><%= article.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(article.created_at) %> ago.
  </span>
</li>

app/views/articles/article.html.erb
<h1> 詳細情報</h1>

<ul>
    <p><li>Herenowtitle: <%= @article.herenowtitle %></li></p>
    <p><li>title: <%= @article.title %></li></p>
    <p><li>content: </br><%= @article.content %></li></p>	
</ul>

 <section>
      <h1>店舗基本情報</h1>
      <p>店舗名:<%= @article.store.name %></p>
      <p>住所:<%= @article.store.address %></p>
      <p>電話番号:<%= @article.store.tell %></p>
      <p>URL:<%= @article.store.url %></p>
      <p>メールアドレス:<%= @article.store.email %></p>
 </section>

app/views/articles/index.html.erb
<h1> 詳細情報</h1>

<ul>
    <% @articles.each do |article| %>
    <p><li><%= link_to article.herenowtitle+"/", article_path(article.id) %> <%= link_to article.title, article_path(article.id) %></li></p>
    <% end %>
</ul>

app/views/articles/index_eat.html.erb
<h1> 詳細情報</h1>

<ul>
    <% @articles.each do |article| %>
    <p><li><%= link_to article.herenowtitle+"/", article_path(article.id) %> <%= link_to article.title, article_path(article.id) %></li></p>
    <% end %>
</ul>

app/views/articles/new.html.erb
<% provide(:title, 'post') %>
<h1>投稿</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@article) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :herenowtitle %>
      <%= f.select :herenowtitle, ['旬', 'お得'], { include_blank: '選択してください' }, class: 'herenow' %>

      <%= f.label :title %>
      <%= f.text_field :title %>

      <%= f.label :content %>
      <%= f.text_area :content %>

      <%= f.label :image %>
      <%= f.file_field :image %>

      <%= f.submit "Post my acrticle", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/articles/show.html.erb
<h1> 詳細情報</h1>

<ul>
    <p><li>Herenowtitle: <%= @article.herenowtitle %></li></p>
    <p><li>title: <%= @article.title %></li></p>
    <p><li>content: </br><%= @article.content %></li></p>
    <p><li><% if @article.image? %>
    	   <%= image_tag @article.image.thumb.url %>
    	     <% else %>
    	   <%= image_tag 'noimage.gif' %>
    	   <% end %><p><li>	
</ul>

 <section>
      <h1>店舗基本情報</h1>
      <p>店舗名:<%= @article.store.name %></p>
      <p>住所:<%= @article.store.address %></p>
      <p>電話番号:<%= @article.store.tell %></p>
      <p>URL:<%= @article.store.url %></p>
      <p>メールアドレス:<%= @article.store.email %></p>
 </section>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    Copyright (C) 2014 Forbeans. All Rights Reserved.
    by Funny Guys
  </small>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "BeansStreet", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-right">
          <li><%= link_to "Home",  root_path %></li>
          <li><%= link_to "about",  about_path  %></li>
          <li><li id="category-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Category
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "食事", "#" %></li>
                <li><%= link_to "shopping", "#" %></li>
              </ul>
          </li>
           <% if signed_in? %>
            <li><%= link_to "投稿", new_article_path %></li>
            <li id="fat-menu" class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                Account <b class="caret"></b>
              </a>
              <ul class="dropdown-menu">
                <li><%= link_to "Profile", current_store %></li>
                <li><%= link_to "投稿記事一覧", articles_path %></li>
                <li class="divider"></li>
                <li>
                  <%= link_to "Sign out", signout_path, method: "delete" %>
                </li>
              </ul>
            </li>
          <% else %>
            <li><%= link_to "投稿（Sign in）", signin_path %></li>
          <% end %>
        </ul>
      </nav>
    </div>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= stylesheet_link_tag "application", media: "all",
                                           "data-turbolinks-track" => true %>
    <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |key, value| %>
        <div class="alert alert-<%= key %>"><%= value %></div>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/locations/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@location) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :latitude %>
      <%= f.text_field :latitude %>

      <%= f.label :longitude %>
      <%= f.text_field :longitude %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/locations/show.html.erb
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> ↵
    (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul<% title "Location" %>

<p>
  <strong>Address:</strong>
  <%= @location.address %>
</p>
<p>
  <strong>Latitude:</strong>
  <%= @location.latitude %>
</p>
<p>
  <strong>Longitude:</strong>
  <%= @location.longitude %>
</p>

<h3>Nearby Locations</h3>
<ul>
<% for location in @location.nearbys(10) %>
  <li><%= link_to location.address, location %> ↵
    (<%= location.distance.round(2) %> miles)</li>
<% end %>
</ul>

<p>
  <%= link_to "Edit", edit_location_path(@location) %> |
  <%= link_to "Destroy", @location, :confirm => ↵
    'Are you sure?', :method => :delete %> |
  <%= link_to "View All", locations_path %>
</p>

app/views/segments/index_eat.html.erb
<% provide(:title, 'Home') %>
<div class="center hero-unit">
  <h1>Let's enjoy HereNow!!</h1>
<p><% @segment.articles.each do |article| %>
   <%= article %> 
   <% end %>
</p>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-error">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li>* <%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/about.html.erb
<% provide(:title, 'about') %>
<h1>What is "BeansStreet"</h1>
<h2>「今、ここにしかない」最高な、旬な、お得なものをお届けします</h2>
<p>ちょっとした時間に覗けば、あたなの知らないこの瞬間の素敵なものに出会えるかもしれない</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home') %>
  <h1>Let's enjoy HereNow!!</h1>
<ul>
  <div class="row">
   <div class="col-md-6 portfolio-item">
    <% @articles.each do |article| %>
    <li style="list-style:none;">
    	<a href = "#">
    	<img class="img-responsive" 
    	<%= image_tag article.image.thumb.url, :size => '600x300' %> </a>
    	<h3><%= link_to article.herenowtitle, article_path(article.id) %></h3> 
    	<h3><%= link_to article.title, article_path(article.id) %></h3>
    	  <%= time_ago_in_words(article.created_at) %> ago.</li></p>
    <% end %>
   </div>
  </div>
</ul>

app/views/stores/confirm.html.erb
<h2><%= @store %></h2>

<ul>
<% @store.articles.each do |article| %>
  <li><%= article.herenowtitle %> </li>
<% end %>
</ul>

app/views/stores/new.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="span6 offset3">
    <%= form_for(@store) do |f| %>
     <%= render 'shared/error_messages', object: f.object %>

      <%= f.fields_for :segment do |f_segment| %>
          <%= f_segment.label :'業態' %>
          <%= f_segment.select :name, ['食事', 'shopping', 'その他'], { include_blank: 
            '選択してください' }, class: 'segment' %>
      <% end %>

      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.text_field :email %>

      <%= f.label :address %>
      <%= f.text_field :address %>

      <%= f.label :tell %>
      <%= f.text_field :tell %>

      <%= f.label :url %>
      <%= f.text_field :url %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-large btn-primary" %>
    <% end %>
  </div>
</div>

app/views/stores/show.html.erb
<% provide(:title, @store.name) %>
<div class="row">
  <aside class="span4">
    <section>
      <h1>
        <%= @store.name %>
      </h1>
      <p>基本情報</p>
      <p>住所:<%= @store.address %></p>
      <p>電話番号:<%= @store.tell %></p>
      <p>URL:<%= @store.url %></p>
      <p>メールアドレス:<%= @store.email %></p>
    </section>
  </aside>
</div>

app/views/stores/showcontent.html.erb
　 <div class="span8">
    <% if @store.articles.any? %>
      <h3>Articles (<%= @store.articles.count %>)</h3>
      <ol class="articles">
        <%= render @articles %>
      </ol>
      <%= will_paginate @articles %>
      <%= link_to "Sign up now!", class: "btn btn-large btn-primary" %>
    <% end %>